### ISSUE TITLE
В vmap2/Makefile требуется отсутствующий файл vmap2io_gpx.cpp

### ISSUE THREAD

**Issue by ioctl-user** [slazav/mapsoft2-libs#2]

**Comment by ioctl-user** [comment]
Без него mapsoft2 не собирается.

**Comment by slazav** [comment]
Прошу прощения, прозевал. Теперь все исправлено

**Comment by slazav** [comment]
Выяснил, что у меня на github довольно давно отвалились уведомления. Поправил, теперь надеюсь реагировать быстрее.
