### ISSUE TITLE
Ошибка теста conv_geo.test

### ISSUE THREAD

**Issue by ioctl-user** [slazav/mapsoft2-libs#3]
При сборке тест conv_geo.test выдаёт ошибку:

```make[2]: вход в каталог «/home/build/mapsoft2/modules/geo_data»
## Running test: conv_geo.test
Error: assert_err: conv_geo.test.cpp:218: error is not thrown:
command: cnv1.frw(p1)
expected error: Can't convert coordinates: Point outside of projection domain

make[2]: *** [../Makefile.inc:107: conv_geo.test.passed] Ошибка 1
```

Та же ошибка есть в тесте, который расположен на 15 строк ниже. Сообщение то же:
```expected error: Can't convert coordinates: Point outside of projection domain```

Системная версия proj 9.2.1 , проявляется на коммитах 064134d260b3a7238702e356a9f04a10ce8fab85 и 0d95f4102f571900989ff7d1bf629ebbcd0ac41c .

**Comment by slazav** [comment]
Что-то я прозевал это сообщение. Это все по-разному работает с разными версиями proj.
Насколько я понимаю, это было исправлено в https://github.com/slazav/mapsoft2-libs/commit/9300f93e171769bbf8710d9dfa5f2724b7b6142d
Закрываю, если опять вылезет - переоткрой
